name: Simple Fancy Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Clone Nest JS starter
        run: git clone https://github.com/nestjs/typescript-starter.git;
             mv typescript-starter nest-js-app
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/nest-js-app:latest .
          docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/nest-js-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: SSH Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop nest-js-app || true
            docker rm nest-js-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/nest-js-app:latest
            docker run -d --restart=always --name nest-js-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nest-js-app:latest
